name: NyEconomy
main: com.mc9y.com.mc9y.nyeconomy.Main
softdepend:
  - PlaceholderAPI
  - PokemonAPI
version: ${project.version}
commands:
  nyeconomy:
    description: Command for NyEconomy
    aliases:
      - ne
      - neco
      - nyeco
      - nye