name: NyEconomy
main: com.mc9y.nyeconomy.Main
depend:
  - PokemonAPI
softdepend:
  - PlaceholderAPI
  - Vault
version: ${project.version}
commands:
  nyeconomy:
    description: Command for NyEconomy
    aliases:
      - ne
      - neco
      - nyeco
      - nye