name: NyEconomy
main: com.mc9y.nyeconomy.Main
depend:
  - AyCore
softdepend:
  - PlaceholderAPI
  - Vault
api-version: 1.13
version: ${project.version}
commands:
  nyeconomy:
    description: Command for NyEconomy
    aliases:
      - ne
      - neco
      - nyeco
      - nye
folia-supported: true